### ISSUE TITLE
ubuntu, debian

### ISSUE THREAD

**Issue by ser** [upmaru/opsmaru-images#2]
ubuntu: noble, jammy, devel
debian: bookworm, sid

**Comment by zacksiri** [comment]
Coming right up! I'll try and get this sorted within this coming week.

**Comment by zacksiri** [comment]
@ser based on my checking `devel` currently points to `noble` They are essentially the same at this point in time. When this change (canonical starts developing a new release) we can build the `devel` release as well.

So for the ubuntu for now I will add `noble` and `jammy`

**Comment by zacksiri** [comment]
Ubuntu noble is now live.
