### ISSUE TITLE
centos-8,9-streams images

### ISSUE THREAD

**Issue by aivanise** [upmaru/opsmaru-images#7]
please add centos 8 and 9 streams images

**Comment by zacksiri** [comment]
Will get this done this week. Apologies for the delay.

**Comment by aivanise** [comment]
no worries, take your time, appreciate your good work very much!

**Comment by zacksiri** [comment]
This is now completed!

You should see it on https://images.opsmaru.com now

<img width="1251" alt="Screenshot 2567-03-13 at 17 10 42" src="https://github.com/upmaru/opsmaru-images/assets/134488/d652f6eb-df55-4e33-b9ac-af6a93bb66be">

**Comment by aivanise** [comment]
many thanks, not sure what is going on but our packer still miraculously works with images: remote, but now we are ready once it stops ;)

**Comment by zacksiri** [comment]
@aivanise yeah, essentially `images:` will work for you until May
